---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: pipeline
spec:
  template:
    metadata:
      labels:
        app: pipeline
    spec:
      hostname: pipeline
      containers:
      - name: pipeline
        ports:
          - containerPort: 5044
            name: filebeat
          - containerPort: 9600
            name: logstash
        image: docker.elastic.co/logstash/logstash:7.7.0
        volumeMounts:
        - name: apache-log-pipeline-config
          mountPath: /usr/share/logstash/pipeline/
        command:
        - logstash
      volumes:
      - name: apache-log-pipeline-config
        configMap:
          name: apache-log-pipeline
          items:
          - key: apache-log-es.conf
            path: apache-log-es.conf
---
kind: Service
apiVersion: v1
metadata:
  name: apache-log-pipeline
spec:
  type: NodePort
  selector:
    app: pipeline
  ports:
  - protocol: TCP
    port: 5044
    targetPort: 5044
    nodePort: 30102
    name: filebeat
  - protocol: TCP
    port: 9600
    targetPort: 9600
    name: logstash
---
