persistence:
  enabled: false

service: 
  annotations: 
  type: LoadBalancer
  ports:
    - name: beats
      port: 5044
      protocol: TCP
      targetPort: 5044
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080

logstashConfig:
  logstash.yml: |
    http.host: 0.0.0.0
    xpack.monitoring.enabled: false

logstashPipeline:
  uptime.conf: |
    input { exec { command => "uptime" interval => 30 } }
    output { 
    elasticsearch {
     hosts => ["https://10.0.220.198:9200"] 
     index => "logstash" 
     user => 'elastic'
     password => 'xxxxx'
     } }

  logstash.conf: |
   input {
      exec {
        command => "uptime"
        interval => 30
      }
    }
    output { stdout { } }

  custom-config.conf: |
   input {
      exec {
        command => "uptime"
        interval => 30
      }
    }
    output { stdout { } }
